version: '3.8'

services:
  db:
    image: mongo
    container_name: mongo

  app:
    build: .
    container_name: flask_app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
